### ISSUE TITLE
$CONNECTED 

### ISSUE THREAD

**Issue by harvybob** [thomasjsn/rpi-w1therm#1]
Hi,

Firstly, thanks for this script! its just what I was looking for!
I'm just tweeking it for my use, can you let me know where the value of $CONNECTED is populated? or is that done on the OS layer?

**Comment by thomasjsn** [comment]
Hello :)

A `1` message is published to the `$CONNECTED` topic when connecting to the broker, here: https://github.com/thomasjsn/rpi-w1therm/blob/202faa623a915e442fb9bb69d558653903a83a09/temp_sensor.py#L25

And a `0` message is registered as the _last will_, here: https://github.com/thomasjsn/rpi-w1therm/blob/202faa623a915e442fb9bb69d558653903a83a09/temp_sensor.py#L58

Last will means that the broker will publish the message on behalf of the client, should the client disconnect or stop responding.

Hope this help.

**Comment by harvybob** [comment]
Thanks for the info! for some reason the status hasn't come up on my mqtt, but a bit of playing around has found that i need to remove the $ .

I though the $CONNECTED acted as a variable in the script not the actual value hence the question! Thanks for your assistance!

**Comment by thomasjsn** [comment]
Topics starting with $ are "special".

From https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices/

> The $-symbol topics are reserved for internal statistics of the MQTT broker.

They do not show up with wildcard subscriptions, like `#`

**Comment by harvybob** [comment]
Thanks for clarifying! I've removed the $ and am tweaking it to fit into my existing formatting from other tasmota devices.

Thanks for your assistance!
