### ISSUE TITLE
online vs offline

### ISSUE THREAD

**Issue by harvybob** [thomasjsn/rpi-w1therm#2]
Hi, I'm testing the script on a single sensor, your default listed sensors in sensors {} are still in place, with one changed to my actual sensor.

I'm using MQTT explorer (on my PC) to monitor my mosquito queue which is running on Home Assistant.
The sensor and scripts are running on a raspberrypi.

On the first run, the online/offline status is correct in that your default sensors are showing as offline. My sensor is showing as online.

However, when I end the script - using Ctrl+c on the command line, I would expect my sensor to show the state as offline.

Is this what you expect also?

**Comment by thomasjsn** [comment]
That's not quite how it works unfortunately. It's the script that reports the sensors as available. or unavailable, based on the IDs that respond to `get_available_sensors()`.

So if you kill the script, it no longer reports the availability. If you want it to report as unavailable if the script is killed; you can utilize the `$CONNECTED` topic as availability topic instead. It doesn't have to be named `$CONNECTED`, that is just what I use.

**Comment by harvybob** [comment]
thanks - i'll have a play, need to figure out a way to change status for only those devices on this pi - eventually i aim to have this running on 2-3 pi's so don't want the ones that do not have a particular sensor to mark others as offline when they are in the sensor array!
